package io.github.aasaru.drools.section06

import io.github.aasaru.drools.domain.Validation;
import io.github.aasaru.drools.domain.VisaApplication;
import io.github.aasaru.drools.domain.Visa;

rule "Report were visas"
	dialect "mvel"
	//We did not set the any agenda group in this that means this rule will run at the end.
	//Here, we set the activation-group with salience, means it picks only one rule from this whole file at once
	//and if when conditions gets true , then other rule won't get fired of same activation-group else other rule will get fired  
	activation-group "conclusion"
	salience 20
	when
    Visa()
	then
	  System.out.println("Conclusion: at least one visa was issued");
end

rule "Report no visas"
	dialect "mvel"
	activation-group "conclusion"
	salience 10
	when
    VisaApplication( validation == Validation.FAILED )
	then
	  System.out.println("Conclusion: no visas were issued");
end
